name: Generate Simple Index
on:
  push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: generate index
        run: |
          ./index > README.md

      - name: Commit changes
        run: |
          git config --global user.email "qmacro@gmail.com"
          git config --global user.name "DJ Adams"
          git add README.md
          git commit -m 'index rebuild' || exit 0
          git push
